### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by Howard20181** [Smoke-N-Mirrors/-pigai-toolkit#6]
脚本加载失败 
作文https://www.pigai.org/index.php?c=v2&a=write&rid=1746535

**Comment by Smoke-N-Mirrors** [comment]
更新了一下, 但是你这个界面有点特殊(一般的界面禁止了粘贴有提示但这个没有而且为书信体), 所以我直接加了个手动允许粘贴的按钮, 缺点是这个按钮会使得字数统计失效, 凑活用吧qwq
