### ISSUE TITLE
查找相似功能的建议

### ISSUE THREAD

**Issue by RoyMikeJiang** [Smoke-N-Mirrors/-pigai-toolkit#8]
其实也不算bug，只是个建议
这个脚本很强了，给作者点个赞
---issue 模板---
出现问题的网址(如果没有此信息, 问题可能很难解决):
脚本第354行
 let link = `http://www.pigai.org/?c=sort&a=copy5&eid1=${unsafeWindow.eId}&v1=2&rid=${toolkit.getRid(window.location.href.indexOf("rid=") + 4)}&qz=1`;
出现问题的事件(非必填):
只能查看第一版的相似情况，可以更改v1=的值进行修改的其他版本的相似查找，一般是修改的版本+1

**Comment by Smoke-N-Mirrors** [comment]
彳亍
