### ISSUE TITLE
批改网新网址是啥?

### ISSUE THREAD

**Issue by rtyuikk** [Smoke-N-Mirrors/-pigai-toolkit#9]
---issue 模板---
出现问题的网址(如果没有此信息, 问题可能很难解决):

出现问题的事件(非必填):今天打开旧网址，脚本无法像之前一样跳转到新网址了，也无法使用

**Comment by Smoke-N-Mirrors** [comment]
http://www.pigai.org/index.php?c=v2&a=write&rid=******
批改网这东西太乱了, 旧版网址我还没找到一个统一的标志, 所以可会无法跳转, 如果url没有问题那就再控制台输入<code>document.cookie = "old=2017;path=/";
                document.cookie = "old=2017;path=/;domain=pigai.org";</code>然后刷新一下
